name: Build and deploy

on:
  push:
    branches: ["main", "staging"]
  pull_request:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      kafka:
        image: apache/kafka-native
        ports:
          - "9092:9092"
        env:
          # Configure listeners for both docker and host communication
          KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
          KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

          # Settings required for KRaft mode
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

          # Listener to use for broker-to-broker communication
          KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

          # Required for a single node cluster
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test
        env:
          APP_PORT: 9001
          APP_HOST: 0.0.0.0
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/app
          APP_SECRET: sometest_secret
          APP_KAFKA_SERVER: localhost:9092
          DEFAULT_EMAIL_FROM: admin@email.com
          SMTP_HOST: sandbox.smtp.mailtrap.io
          SMTP_USERNAME: "username"
          SMTP_PASSWORD: "password"
          SMTP_PORT: 2525

  # build:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.ref_name == 'main'
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Login to GitHub Container Registry
  #       if: github.ref == 'refs/heads/main'
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.D_GITHUB_TOKEN }}
  #
  #     - name: Build and push Docker image
  #       if: github.ref == 'refs/heads/main'
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest,${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }},${{ env.REGISTRY }}/${{ github.repository }}:prod
