//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use super::sea_orm_active_enums::TenureType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_subscriptions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub account_id: i64,
    pub plan_id: i64,
    pub tenure_type: TenureType,
    pub tenure_duration: i32,
    pub start_date: Date,
    pub end_date: Date,
    pub price: Decimal,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::AccountId",
        to = "super::accounts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "super::subscription_plans::Entity",
        from = "Column::PlanId",
        to = "super::subscription_plans::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    SubscriptionPlans,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::subscription_plans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionPlans.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
