//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::auth_tokens::Entity as AuthTokens;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
