//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "account_status")]
#[serde(rename_all = "snake_case")]
pub enum AccountStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "banned")]
    Banned,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize, Default,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "app_status")]
#[serde(rename_all = "snake_case")]
pub enum AppStatus {
    #[sea_orm(string_value = "active")]
    #[default]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "channel_status")]
#[serde(rename_all = "snake_case")]
pub enum ChannelStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "channel_type")]
#[serde(rename_all = "snake_case")]
pub enum ChannelType {
    #[sea_orm(string_value = "text")]
    Text,
    #[sea_orm(string_value = "video")]
    Video,
    #[sea_orm(string_value = "audio")]
    Audio,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "performance_criteria"
)]
#[serde(rename_all = "snake_case")]
pub enum PerformanceCriteria {
    #[sea_orm(string_value = "reliability")]
    Reliability,
    #[sea_orm(string_value = "latency")]
    Latency,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "subscription_plan_status"
)]
#[serde(rename_all = "snake_case")]
pub enum SubscriptionPlanStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "inactive")]
    Inactive,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tenure_type")]
#[serde(rename_all = "snake_case")]
pub enum TenureType {
    #[sea_orm(string_value = "monthly")]
    Monthly,
    #[sea_orm(string_value = "quarterly")]
    Quarterly,
    #[sea_orm(string_value = "semi_annually")]
    SemiAnnually,
    #[sea_orm(string_value = "yearly")]
    Yearly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "token_type")]
#[serde(rename_all = "snake_case")]
pub enum TokenType {
    #[sea_orm(string_value = "access_token")]
    AccessToken,
    #[sea_orm(string_value = "email_otp")]
    EmailOtp,
    #[sea_orm(string_value = "password_otp")]
    PasswordOtp,
}
