//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use super::sea_orm_active_enums::SubscriptionPlanStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subscription_plans")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub features: String,
    pub max_active_connections: i64,
    pub max_allowed_channels: i64,
    pub max_allowed_apps: i32,
    pub max_throughput_per_second: i64,
    pub max_throughput_per_month: i64,
    pub monthly_cost: Decimal,
    pub status: SubscriptionPlanStatus,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_subscriptions::Entity")]
    AccountSubscriptions,
}

impl Related<super::account_subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountSubscriptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
